blank_issues_enabled: false
contact_links:
  - name: Telegram
    url: https://t.me/+rfvGU6sDSvEwZDgy
    about: Official Telegram group of CofeMine Launcher.
  - name: Discord
    url: https://discord.gg/zyKM2XAnXW
    about: Official Discord server of CofeMine Launcher.
  - name: Other
    url: https://github.com/cofedish/cofemine_launcher/discussions/new/choose
    about: Report other problems in Discussions.
